

stages:
  - test
  - docs

    
build:linux:
  image: python:3.7-buster
  stage: test
  before_script:
    - pip install --upgrade -r requirements.txt
    - pip install pytest-cov
    - pip install .
  script:
    - pytest --cov=. .
    
pages:
  image: python:3.7-buster
  stage: docs
  script:
   - pip install .
   - pip install sphinx
   - pip install sphinx_rtd_theme
   - cd docs
   - make html
   - cd ..
   - mv docs/build/html public
  artifacts:
      paths:
       - public


    




















