image: python:3.7-buster

stages:
  - test
  - docs

    
build:linux:
  stage: test
  before_script:
    - pip install --upgrade -r requirements.txt
    - pip install .
  script:
    - pytest .
<<<<<<< HEAD
=======
    
pages:
  stage: docs
  script:
   - pip install .
   - pip install sphinx
   - pip install sphinx_rtd_theme
   - cd docs
   - make html
   - cd ..
   - mv docs/build/html public
  artifacts:
      paths:
       - public


    




















>>>>>>> 07959c0... Update CI/CD to include build of documentation
