language: python
jobs:
  include:
    - name: "Python 3.7.4 on Xenial Linux"
      python: 3.7.4
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11.2
      language: shell
    - name: "Python 3.7.4 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.7.4
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
install:
  - pip3 install --upgrade pip
  - pip3 install --upgrade -r requirements.txt
  - pip3 install .
script: pytest --cov=. .
